#' b to Beta Converter
#' @export
#' @param m a standard object of type lm()
#' @examples \code{\link{lm.beta(model)}}
#'# model is an lm() object
#' @description Converts b's generated by lm() to Beta.
#' Results are presented in a descending order.
#' @seealso \code{\link{beta2b()}} does the exact opposit.

lm.beta <- function(m){
  b <- c()
  p <- c()
  for(i in 2:length(m$coefficients)){
    b[i-1] <- m$coefficients[i]/
      (sd(m$model[,1])/sd(m$model[,i]))
    p[i-1] <- names(m$coefficients[i])
  }
  f <- data.frame(predictors=p,beta=b)
  return(f[order(abs(f[,2]),decreasing = T),,])
}
