#' b to Beta Converter
#' @export
#' @param m a standard object of type lm()
#' @examples model= lm(Bsum~age+sat,depression)
#' lm.beta(model)
#' @returns A data frame of the betas in an absolute decending order.
#' @description This function converts b's generated by lm() to Beta.
#' Results are presented in a descending order.
#' @seealso \code{\link{beta2b()}} converts Beta back to raw B.

lm.beta <- function(m){
  b <- c()
  p <- c()
  for(i in 2:length(m$coefficients)){
    b[i-1] <- m$coefficients[i]/
      (sd(m$model[,1])/sd(m$model[,i]))
    p[i-1] <- names(m$coefficients[i])
  }
  f <- data.frame(predictors=p,beta=b)
  return(f[order(abs(f[,2]),decreasing = T),,])
}
