#' b to Beta Converter
#' @export
#' @param lm.model a standard object of type \code{lm}
#' @examples model= lm(Bsum~age+sat,depression)
#' lm.beta(model)
#' Gen_model=lm(Generosity~.,happiness)
#' # Generosity predicted by all other variables
#' lm.beta(Gen_model)
#' @returns A data frame of the betas in an absolute descending order.
#' @description This function converts b's generated by \code{\link{lm}} to Beta.
#' Results are presented in a descending order.
#' @seealso \code{\link{beta2b}} converts Beta back to raw B.

lm.beta <- function(lm.model){
  b <- c()
  p <- c()
  for(i in 2:length(lm.model$coefficients)){
    b[i-1] <- lm.model$coefficients[i]/
      (sd(lm.model$model[,1])/sd(lm.model$model[,i]))
    p[i-1] <- names(lm.model$coefficients[i])
  }
  f <- data.frame(predictor=p,beta=b)
  return(f[order(abs(f[,2]),decreasing = T),,])
}
